### ISSUE TITLE
emacs-lisp-package is not a valid syntax checker

### ISSUE THREAD

**Issue by alexmurray** [purcell/flycheck-relint#1]
I just installed this from melpa using `use-package` as:
```emacs-lisp
(use-package flycheck-relint
  :ensure t
  :after flycheck
  :config (flycheck-relint-setup))
```

But when executing the above to install / load this package I get the following error:

```
Error (use-package): flycheck-relint/:config: emacs-lisp-package is not a valid syntax checker
```

I assume `emacs-lisp-package` should instead be replaced with `emacs-lisp` as per https://github.com/flycheck/flycheck/blob/master/flycheck.el#L7724

**Comment by alexmurray** [comment]
Ahh I see this is from flycheck-package - https://github.com/purcell/flycheck-package/blob/master/flycheck-package.el#L60

**Comment by alexmurray** [comment]
I noticed I had `:defer t` in my `use-package flycheck-package` stanza... so it was never actually getting activated.. with this removed it is fine. However I think perhaps this package shouldn't assume `flycheck-package` is installed (since it doesn't require it) and so be more graceful in this regard.

**Comment by purcell** [comment]
> However I think perhaps this package shouldn't assume `flycheck-package` is installed (since it doesn't require it) and so be more graceful in this regard.

Yes indeed.

**Comment by alexmurray** [comment]
Thanks for the quick fix!
