### ISSUE TITLE
Adapt to relint 1.15

### ISSUE THREAD

**Issue by mattiase** [purcell/flycheck-relint#2]
This is just a reminder about the changed interface in relint 1.15 (added level value in the returned tuple); it was an incompatible change. Or perhaps we should change to returning alists (or plists) right away?

**Comment by purcell** [comment]
Thanks, yes, I'd forgotten this but had the changes ready to go pending the release.

**Comment by mattiase** [comment]
I didn't run the code, but it looks like you didn't either. Parameter order confusion?

**Comment by purcell** [comment]
>  it looks like you didn't either

What a shocking claim!

And correct. Guess those changes weren't as "ready to go" as I remembered... :-) Fixed now, thanks.
