### ISSUE TITLE
calling internal relint functions with invalid args

### ISSUE THREAD

**Issue by mattiase** [purcell/flycheck-relint#3]
In this expression (line 50):
```
(mapconcat 'identity
  (append (list message (relint--quote-string str))
                 (when str-idx (list (concat " " (relint--caret-string str str-idx)))))
```
the variable `str` can be nil, and the internal functions `relint--quote-string` and `relint--caret-string` do not handle such arguments. This leads to an error, and flycheck silently giving up on checking that buffer.
Presumably the whole thing should be `(if str (mapconcat ...) message)`.

**Comment by purcell** [comment]
Thanks, I committed what I think should be a reasonable fix.

**Comment by mattiase** [comment]
Works, thanks!

**Comment by purcell** [comment]
Thank you for reporting this and checking the fix.
