### ISSUE TITLE
New relint/xr dev branches

### ISSUE THREAD

**Issue by mattiase** [purcell/flycheck-relint#4]
I'm about to merge the `location` development branches for xr and relint, but since there is a breach of API compatibility, I wonder if you would like to take a look. I certainly don't want to make it too hard for those who provide a user interface.

The main API change is that the `relint-buffer` function returns a list of objects with accessors instead of list-based tuples. There are info-level auxiliary messages, and most diagnostics give a start..end range, not just a single position, so that a UI can show the region of interest in the buffer.

Otherwise I'll just go ahead and release new versions of both packages and leave you to deal with the change.

**Comment by purcell** [comment]
Don't let me hold you up — I'll check at some point, but I'm not actively using this package currently.

**Comment by purcell** [comment]
Thanks for the heads-up!

**Comment by mattiase** [comment]
All right, here goes then: the new versions have now been released. (It usually takes a few hours for GNU ELPA to notice and make the packages available.)

**Comment by purcell** [comment]
Hmm, I guess it didn't rebuild yet...

**Comment by mattiase** [comment]
Mostly my fault, sorry – the ELPA bot only updates packages when their version number changes and somehow I had the commits doing that sitting unpushed in my tree until this morning. I'll give it another 12 hours before asking the admins.

**Comment by purcell** [comment]
Hah, no worries, I just happened to take a look and was surprised to not find an update.

**Comment by mattiase** [comment]
Now they are there, finally. Had a false start when the bot had received both xr and relint at the same time and decided to process relint first, found the it didn't build (because it required the new xr version) and shouted me a nasty mail. But it seems to have redeemed itself the following cycle some hours later. Cheers for that.

**Comment by mattiase** [comment]
Although I'm not actually using this package myself, it is of quite some interest as a validation of the relint API, so I took it upon myself to complete the port to relint 2.0.

Things I learned by doing so:
* It basically works, so the API is probably fine
* It seems fast enough not to require running asynchronously (in an external Emacs process)
* Flycheck sorts all diagnostics by location, which means that an info-level notes that supply useful information about warnings may appear in the wrong order if the info location is earlier in the source buffer. This affects all checkers including C compilers, and is pretty annoying.
* We are forced to use the same silly ASCII caret to highlight the error location in a regexp – using faces to highlight the problematic parts would be much better but flycheck doesn't let us do that. In a tooltip even the ASCII caret is useless because of the proportional font.

Anyway, I could send you the patch (or post a PR) if it would be useful to you.

**Comment by purcell** [comment]
Yes, a PR would be most welcome!

> Flycheck sorts all diagnostics by location, which means that an info-level notes that supply useful information about warnings may appear in the wrong order if the info location is earlier in the source buffer. This affects all checkers including C compilers, and is pretty annoying.

I suspect that in Flycheck's list view it may be possible to sort by error level. But yeah, at least this behaviour is consistent across checkers, even if it's not your preferred choice.

> We are forced to use the same silly ASCII caret to highlight the error location in a regexp – using faces to highlight the problematic parts would be much better but flycheck doesn't let us do that. In a tooltip even the ASCII caret is useless because of the proportional font.

I wonder... could you return the error location as the exact location of the caret, rather than the extent of the regexp? (I have a feeling that one or both of Flycheck and Flymake typically extend the error extents to the word at point, so this might not work.)

**Comment by mattiase** [comment]
> I suspect that in Flycheck's list view it may be possible to sort by error level. But yeah, at least this behaviour is consistent across checkers, even if it's not your preferred choice.

Sorting by error level just gives a scrambled list of diagnostics. What would be useful is a way to give Flycheck a grouped list, where the diagnostics in each group will stay together even when sorted, and sorting would use the location of the first diagnostic in the group.

Ideally, Flycheck wouldn't even highlight the auxiliary (info-level) locations in the buffer at all until the user selects their parent warning/error, because the info locations aren't interesting by themselves – they'd just be something like "which was first declared here".

> I wonder... could you return the error location as the exact location of the caret, rather than the extent of the regexp? (I have a feeling that one or both of Flycheck and Flymake typically extend the error extents to the word at point, so this might not work.)

Relint does return the exact location if the regexp is present as a string literal in the source, and a field that indicates whether this is the case. But Flycheck will happily highlight all parts of the source that has some kind of diagnostics referring to it so it can be hard to see which one applies to a particular warning, in the not-too-uncommon case when a regexp has multiple problems, perhaps even overlapping.

Ideally the user would select an error/warning (with auxiliary info-level notes) and automatically have its location(s) marked until something else is selected.

**Comment by mattiase** [comment]
This is finished then, more or less. Maybe we should do something about flycheck's (and flymake's) problems one day.

Both may need some gearing-up to satisfy the needs of static analysis tools that often have quite complex stories to present, and often the presentation alone is a substantial difficulty in writing the tool. A user who doesn't understand a report is much more likely to ignore it or turn off the checker entirely.

Flycheck and flymake assume that each finding can be summarised in a short line that points to one spot in the code, and this isn't true even for compilation warnings these days.

**Comment by purcell** [comment]
Personally I've moved to using only `flymake`, but I made a `flymake-flycheck` package so that I can re-use some `flycheck` backends with `flymake`. Definitely agree that both are somewhat basic overall, in the ways you mention.

**Comment by mattiase** [comment]
Flycheck and flymake are indeed very similar in capabilities. Flycheck displays multi-line diagnostics messages in the table-view buffer; flymake doesn't (truncates at the first newline), which means that relint's quoted regexp string won't make it there. The truncated message is also used in tooltips and eldoc's echo line, although flymake's use of eldoc seems to clash with that of emacs-lisp-mode.

There is a new flymake maintainer; we might want to suggest some improvements.

**Comment by mattiase** [comment]
Actually, `flycheck` does have a `group` parameter that could be used so we might as well do that here; that's what PR #8 is about. Didn't seem much use of it, but at least `flycheck-inline` does, although it's of limited value when the relate drags are on the same line which is very common for relint.

Somewhat related: emacs-lsp/lsp-mode#3279
